[package]
name = "anvil-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "anvil"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
anvil-core = { path = "../anvil-core" }
anvil-protocol = { path = "../anvil-protocol" }
base64.workspace = true
clap.workspace = true
chrono.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
